spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springDB?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mjcuser
    password: 2222

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.examplecoop.animalex.animal
  configuration:
    map-underscore-to-camel-case: true

