spring:
  application:
    name: cinema_jpa
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/SPA_DB?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: spauser
    password: 12345
  mustache:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    charset: UTF-8
    servlet:
      cache: false
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate: #???? ??? ????? JPA ??
      ddl-auto: update

server:
  port: 8083
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

