spring:
  application:
    name: food_jpa
  datasource:
    url: jdbc:mysql://localhost:3306/FOOD_DB?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: food_user
    password: food_4321@
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

  mustache:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    charset: UTF-8
    servlet:
      cache: false
server:
  port: 8085
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


